# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4fdd3538ce93cefae1dddd29a2d40c67f482c47b2f02c65f49d3be3e36d47c76d338eb111aaf8371ccb47e68603b93f24b07ea58676bf659cedff162f2ce42a
  mailer_username: <%= ENV["MAILER_USERNAME"] %>
  mailer_api_key: <%= ENV["MAILER_API_KEY"] %>
  sentry_dsn: "<%= ENV["SENTRY_DSN"] %>"
  database:
    :username: <%= ENV['DATABASE_USERNAME'] %>
    :password: <%= ENV['DATABASE_PASSWORD'] %>
test:
  secret_key_base: 1c4530240a66a37466a70199d67e35ebef9faa408fc2689b05c379fcb9ca1a4434944a8e22dcdcd6cd7706c528bf6640d45af772db394a2d45d38e90350b8f26
  mailer_username: <%= ENV["MAILER_USERNAME"] %>
  mailer_api_key: <%= ENV["MAILER_API_KEY"] %>
  sentry_dsn: "<%= ENV["SENTRY_DSN"] %>"
  database:
    :username: <%= ENV['DATABASE_USERNAME'] %>
    :password: <%= ENV['DATABASE_PASSWORD'] %>
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  mailer_username: <%= ENV["MAILER_USERNAME"] %>
  mailer_api_key: <%= ENV["MAILER_API_KEY"] %>
  sentry_dsn: "<%= ENV["SENTRY_DSN"] %>"
  database:
    :username: <%= ENV['DATABASE_USERNAME'] %>
    :password: <%= ENV['DATABASE_PASSWORD'] %>
