require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe SocialBodiesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # SocialBody. As you add validations to SocialBody, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SocialBodiesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all social_bodies as @social_bodies" do
      social_body = SocialBody.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:social_bodies)).to eq([social_body])
    end
  end

  describe "GET #show" do
    it "assigns the requested social_body as @social_body" do
      social_body = SocialBody.create! valid_attributes
      get :show, {:id => social_body.to_param}, valid_session
      expect(assigns(:social_body)).to eq(social_body)
    end
  end

  describe "GET #new" do
    it "assigns a new social_body as @social_body" do
      get :new, {}, valid_session
      expect(assigns(:social_body)).to be_a_new(SocialBody)
    end
  end

  describe "GET #edit" do
    it "assigns the requested social_body as @social_body" do
      social_body = SocialBody.create! valid_attributes
      get :edit, {:id => social_body.to_param}, valid_session
      expect(assigns(:social_body)).to eq(social_body)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new SocialBody" do
        expect {
          post :create, {:social_body => valid_attributes}, valid_session
        }.to change(SocialBody, :count).by(1)
      end

      it "assigns a newly created social_body as @social_body" do
        post :create, {:social_body => valid_attributes}, valid_session
        expect(assigns(:social_body)).to be_a(SocialBody)
        expect(assigns(:social_body)).to be_persisted
      end

      it "redirects to the created social_body" do
        post :create, {:social_body => valid_attributes}, valid_session
        expect(response).to redirect_to(SocialBody.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved social_body as @social_body" do
        post :create, {:social_body => invalid_attributes}, valid_session
        expect(assigns(:social_body)).to be_a_new(SocialBody)
      end

      it "re-renders the 'new' template" do
        post :create, {:social_body => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested social_body" do
        social_body = SocialBody.create! valid_attributes
        put :update, {:id => social_body.to_param, :social_body => new_attributes}, valid_session
        social_body.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested social_body as @social_body" do
        social_body = SocialBody.create! valid_attributes
        put :update, {:id => social_body.to_param, :social_body => valid_attributes}, valid_session
        expect(assigns(:social_body)).to eq(social_body)
      end

      it "redirects to the social_body" do
        social_body = SocialBody.create! valid_attributes
        put :update, {:id => social_body.to_param, :social_body => valid_attributes}, valid_session
        expect(response).to redirect_to(social_body)
      end
    end

    context "with invalid params" do
      it "assigns the social_body as @social_body" do
        social_body = SocialBody.create! valid_attributes
        put :update, {:id => social_body.to_param, :social_body => invalid_attributes}, valid_session
        expect(assigns(:social_body)).to eq(social_body)
      end

      it "re-renders the 'edit' template" do
        social_body = SocialBody.create! valid_attributes
        put :update, {:id => social_body.to_param, :social_body => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested social_body" do
      social_body = SocialBody.create! valid_attributes
      expect {
        delete :destroy, {:id => social_body.to_param}, valid_session
      }.to change(SocialBody, :count).by(-1)
    end

    it "redirects to the social_bodies list" do
      social_body = SocialBody.create! valid_attributes
      delete :destroy, {:id => social_body.to_param}, valid_session
      expect(response).to redirect_to(social_bodies_url)
    end
  end

end
